var nombre = "lilieth";
var apellido = "chacon";
var nombreCompleto = nombre + "" + apellido;
console.log(nombreCompleto);
var nombreCompleto2 = "lilieth" +" "+ "chacon";
console.log(nombreCompleto2);
var juntos = nombre + 219;
console.log(juntos);
juntos = nombre + 78 + 17;
console.log(juntos);
nombre += apellido;
console.log(nombre);